DROP TRIGGER TREMPLOYEEID;
DROP TRIGGER TRCREDID;

CREATE SEQUENCE SQ_SQREIMBURSEMENTID_PK
START WITH 1000
INCREMENT BY 1;
/
CREATE SEQUENCE SQ_SQEMPLOYEEID_PK
START WITH 1000
INCREMENT BY 1;
/
CREATE SEQUENCE SQ_SQCREDID_PK
START WITH 1000
INCREMENT BY 1;
/


CREATE TRIGGER TRREIMBURSEMENTID
BEFORE INSERT ON REIMBURSEMENT
FOR EACH ROW
BEGIN
    SELECT SQ_SQREIMBURSEMENTID_PK.NEXTVAL INTO :NEW.REIMBURSEMENTID FROM DUAL;
END;
/
CREATE TRIGGER TREMPLOYEEID
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_SQEMPLOYEEID_PK.NEXTVAL INTO :NEW.EMPLOYEEID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TRCREDID
BEFORE INSERT ON CREDENTIALS
FOR EACH ROW
BEGIN
    SELECT SQ_SQCREDID_PK.NEXTVAL INTO :NEW.EMPLOYEEID FROM DUAL;
END;
/