DROP TABLE BEAR;
DROP TABLE BEAR_BEEHIVE;
DROP TABLE BEAR_TYPE;
DROP TABLE BEEHIVE;
DROP TABLE CAVE;

CREATE TABLE EMPLOYEE (
EMPLOYEEID NUMBER NOT NULL,
LASTNAME VARCHAR2(20) NOT NULL,
FIRSTNAME VARCHAR2(20) NOT NULL,
TITLE VARCHAR2(30),
REPORTSTO NUMBER,
BIRTHDATE DATE,
HIREDATE DATE,
ADDRESS VARCHAR2(70),
CITY VARCHAR2(40),
STATE VARCHAR2(40),
COUNTRY VARCHAR2(40),
POSTALCODE VARCHAR2(10),
PHONE VARCHAR2(24),
EMAIL VARCHAR2(60),
CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEEID)
);

INSERT INTO EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, REPORTSTO, BIRTHDATE, HIREDATE, ADDRESS, CITY, STATE, COUNTRY, POSTALCODE, PHONE, EMAIL)
VALUES (1,'Scott', 'Michael', 'Sales Representative', 2, TO_DATE('1995-2-18 00:00:00','yyyy-mm-dd hh24:mi:ss'), 
TO_DATE('2017-8-14 00:00:00','yyyy-mm-dd hh24:mi:ss'), '6666 N Stewart St', 'Austin', 'TX', 

